# Generated by Django 3.0.4 on 2020-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200327_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.CharField(max_length=100, verbose_name='User email')),
                ('password', models.CharField(max_length=100, verbose_name='User password')),
            ],
        ),
    ]
